// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayRexApplication.Data;

#nullable disable

namespace PayRex.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217194620_newMigration")]
    partial class newMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PayRexApplication.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attendanceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employeeId");

                    b.Property<int?>("LateMinutes")
                        .HasColumnType("int")
                        .HasColumnName("lateMinutes");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit")
                        .HasColumnName("locked");

                    b.Property<decimal?>("OvertimeHours")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("overtimeHours");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.Property<TimeOnly?>("TimeIn")
                        .HasColumnType("time")
                        .HasColumnName("timeIn");

                    b.Property<TimeOnly?>("TimeOut")
                        .HasColumnType("time")
                        .HasColumnName("timeOut");

                    b.Property<decimal?>("TotalHoursWorked")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("totalHoursWorked");

                    b.Property<int?>("UndertimeMinutes")
                        .HasColumnType("int")
                        .HasColumnName("undertimeMinutes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("AttendanceId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("attendanceRecords");
                });

            modelBuilder.Entity("PayRexApplication.Models.AttendanceScan", b =>
                {
                    b.Property<int>("ScanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("scanId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScanId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("deviceId");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employeeId");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("remarks");

                    b.Property<int>("Result")
                        .HasColumnType("int")
                        .HasColumnName("result");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("scanTime");

                    b.Property<int>("ScanType")
                        .HasColumnType("int")
                        .HasColumnName("scanType");

                    b.HasKey("ScanId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScanTime");

                    b.ToTable("attendanceScans");
                });

            modelBuilder.Entity("PayRexApplication.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auditId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("action");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("EntityAffected")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("entityAffected");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ipAddress");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("newValues");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("oldValues");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Target")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("target");

                    b.Property<string>("TargetId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("targetId");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("userAgent");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("AuditId");

                    b.HasIndex("Action");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("auditLogs");
                });

            modelBuilder.Entity("PayRexApplication.Models.BillingInvoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoiceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dueDate");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("invoiceNumber");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasFilter("[invoiceNumber] IS NOT NULL");

                    b.ToTable("billingInvoices");
                });

            modelBuilder.Entity("PayRexApplication.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("address");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("companyCode");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("companyName");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("contactEmail");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contactPhone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("logoUrl");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("planId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Tin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("CompanyId");

                    b.HasIndex("CompanyCode")
                        .IsUnique();

                    b.HasIndex("CompanyName");

                    b.HasIndex("PlanId");

                    b.ToTable("companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            CompanyCode = "0000",
                            CompanyName = "PayRex System",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PlanId = 3,
                            Status = 0
                        },
                        new
                        {
                            CompanyId = 2,
                            CompanyCode = "1001",
                            CompanyName = "Demo Company",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PlanId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("PayRexApplication.Models.CompanySetting", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<decimal>("AbsentRate")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("absentRate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<decimal>("HolidayRate")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("holidayRate");

                    b.Property<int>("LateGraceMinutes")
                        .HasColumnType("int")
                        .HasColumnName("lateGraceMinutes");

                    b.Property<decimal>("OvertimeRate")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("overtimeRate");

                    b.Property<int>("PayrollCycle")
                        .HasColumnType("int")
                        .HasColumnName("payrollCycle");

                    b.Property<string>("RolesJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("rolesJson");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.Property<decimal?>("WorkHoursPerDay")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("workHoursPerDay");

                    b.HasKey("CompanyId");

                    b.ToTable("companySettings");
                });

            modelBuilder.Entity("PayRexApplication.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employeeNumber");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeNumber"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("birthdate");

                    b.Property<string>("CivilStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("civilStatus");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contactNumber");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("employeeCode");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastName");

                    b.Property<string>("PagIbig")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("pagIbig");

                    b.Property<string>("PhilHealth")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("philHealth");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    b.Property<string>("SSS")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("sss");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("startDate");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("TIN")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("tin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("EmployeeNumber");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyId", "EmployeeCode")
                        .IsUnique();

                    b.ToTable("employees");
                });

            modelBuilder.Entity("PayRexApplication.Models.EmployeeBenefit", b =>
                {
                    b.Property<int>("BenefitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("benefitId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenefitId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employeeId");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("bit")
                        .HasColumnName("isTaxable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("BenefitId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("employeeBenefits");
                });

            modelBuilder.Entity("PayRexApplication.Models.EmployeeDeduction", b =>
                {
                    b.Property<int>("DeductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("deductionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeductionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employeeId");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("endDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<bool>("Recurring")
                        .HasColumnType("bit")
                        .HasColumnName("recurring");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("startDate");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("DeductionId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("employeeDeductions");
                });

            modelBuilder.Entity("PayRexApplication.Models.EmployeeQrCode", b =>
                {
                    b.Property<int>("QrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("qrId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QrId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employeeId");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiresAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("issuedAt");

                    b.Property<string>("QrValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("qrValue");

                    b.HasKey("QrId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("QrValue")
                        .IsUnique();

                    b.ToTable("employeeQrCodes");
                });

            modelBuilder.Entity("PayRexApplication.Models.EmployeeRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<decimal?>("BasicRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("basicRate");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("RateType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rateType");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("roleName");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("RoleId");

                    b.HasIndex("CompanyId");

                    b.ToTable("employeeRoles");
                });

            modelBuilder.Entity("PayRexApplication.Models.GovernmentContribution", b =>
                {
                    b.Property<int>("ContributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contributionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContributionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employeeId");

                    b.Property<decimal>("EmployeeShare")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("employeeShare");

                    b.Property<decimal>("EmployerShare")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("employerShare");

                    b.Property<int>("PayrollPeriodId")
                        .HasColumnType("int")
                        .HasColumnName("payrollPeriodId");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("ContributionId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayrollPeriodId");

                    b.HasIndex("EmployeeId", "PayrollPeriodId", "Type")
                        .IsUnique();

                    b.ToTable("governmentContributions");
                });

            modelBuilder.Entity("PayRexApplication.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoiceId");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paidAt");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("provider");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("referenceNo");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ReferenceNo");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("PayRexApplication.Models.PayrollApproval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("approvalId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approvedAt");

                    b.Property<int>("ApprovedBy")
                        .HasColumnType("int")
                        .HasColumnName("approvedBy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("PayrollPeriodId")
                        .HasColumnType("int")
                        .HasColumnName("payrollPeriodId");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("remarks");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("ApprovalId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("PayrollPeriodId");

                    b.ToTable("payrollApprovals");
                });

            modelBuilder.Entity("PayRexApplication.Models.PayrollPeriod", b =>
                {
                    b.Property<int>("PayrollPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payrollPeriodId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayrollPeriodId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("endDate");

                    b.Property<string>("PeriodName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("periodName");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("startDate");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("PayrollPeriodId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "StartDate", "EndDate")
                        .IsUnique();

                    b.ToTable("payrollPeriods");
                });

            modelBuilder.Entity("PayRexApplication.Models.PayrollSummary", b =>
                {
                    b.Property<int>("PayrollSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payrollSummaryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayrollSummaryId"));

                    b.Property<decimal?>("Allowances")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("allowances");

                    b.Property<decimal?>("BasicPay")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("basicPay");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employeeId");

                    b.Property<decimal>("GrossPay")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("grossPay");

                    b.Property<decimal?>("HolidayPay")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("holidayPay");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("netPay");

                    b.Property<decimal?>("OvertimePay")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("overtimePay");

                    b.Property<int>("PayrollPeriodId")
                        .HasColumnType("int")
                        .HasColumnName("payrollPeriodId");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("totalDeductions");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("PayrollSummaryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayrollPeriodId");

                    b.HasIndex("PayrollPeriodId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("payrollSummaries");
                });

            modelBuilder.Entity("PayRexApplication.Models.Payslip", b =>
                {
                    b.Property<int>("PayslipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payslipId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayslipId"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("generatedAt");

                    b.Property<int>("PayrollSummaryId")
                        .HasColumnType("int")
                        .HasColumnName("payrollSummaryId");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("pdfPath");

                    b.Property<bool>("Released")
                        .HasColumnType("bit")
                        .HasColumnName("released");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("releasedAt");

                    b.HasKey("PayslipId");

                    b.HasIndex("PayrollSummaryId")
                        .IsUnique();

                    b.ToTable("payslips");
                });

            modelBuilder.Entity("PayRexApplication.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subscriptionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("endDate");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("planId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("startDate");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PlanId");

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("PayRexApplication.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("planId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<int>("BillingCycle")
                        .HasColumnType("int")
                        .HasColumnName("billingCycle");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("MaxEmployees")
                        .HasColumnType("int")
                        .HasColumnName("maxEmployees");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("PlanUserLimit")
                        .HasColumnType("int")
                        .HasColumnName("planUserLimit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("PlanId");

                    b.HasIndex("Name");

                    b.ToTable("subscriptionPlans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            BillingCycle = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "For small to medium Filipino businesses",
                            MaxEmployees = 50,
                            Name = "Basic",
                            PlanUserLimit = 3,
                            Price = 2499.00m,
                            Status = 0
                        },
                        new
                        {
                            PlanId = 2,
                            BillingCycle = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "For growing Philippine enterprises",
                            MaxEmployees = 200,
                            Name = "Pro",
                            PlanUserLimit = 10,
                            Price = 4999.00m,
                            Status = 0
                        },
                        new
                        {
                            PlanId = 3,
                            BillingCycle = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Unlimited employees with dedicated support",
                            MaxEmployees = 10000,
                            Name = "Enterprise",
                            Price = 9999.00m,
                            Status = 0
                        });
                });

            modelBuilder.Entity("PayRexApplication.Models.SystemSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("settingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("effectiveDate");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("note");

                    b.Property<decimal>("PagIbigPercentage")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("pagIbigPercentage");

                    b.Property<decimal>("PhilHealthPercentage")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("philHealthPercentage");

                    b.Property<decimal>("SssPercentage")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("sssPercentage");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("SettingId");

                    b.HasIndex("EffectiveDate");

                    b.ToTable("systemSettings");

                    b.HasData(
                        new
                        {
                            SettingId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Initial Philippine government contribution rates for 2025",
                            PagIbigPercentage = 2.0m,
                            PhilHealthPercentage = 2.25m,
                            SssPercentage = 4.5m
                        });
                });

            modelBuilder.Entity("PayRexApplication.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("firstName");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isTwoFactorEnabled");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastName");

                    b.Property<DateTime?>("LastPasswordChangeAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastPasswordChangeAt");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("mustChangePassword");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("passwordHash");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("passwordResetTokenExpiry");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("passwordResetTokenHash");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("profileImageUrl");

                    b.Property<string>("RecoveryCodesHash")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("recoveryCodesHash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<string>("SignatureUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("signatureUrl");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("TotpSecretKey")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("totpSecretKey");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "partozajohnrex@gmail.com",
                            FirstName = "John Rex",
                            IsTwoFactorEnabled = true,
                            LastName = "Partoza",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$Q1Rge9ElQ/AiDCPK6izUTOHPRDyp8VKsGNs/URSR4hV3s0jEteYV.",
                            Role = 0,
                            Status = 0,
                            TotpSecretKey = "JBSWY3DPEHPK3PXP"
                        },
                        new
                        {
                            UserId = 2,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.admin@example.com",
                            FirstName = "Alice",
                            IsTwoFactorEnabled = false,
                            LastName = "Admin",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$6QRhTy7DMFdQ28Ax/SrKcOncut4.3WtzdMFRTNO5j3KjDkZQIUO3q",
                            Role = 1,
                            Status = 0
                        },
                        new
                        {
                            UserId = 3,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hannah.hr@example.com",
                            FirstName = "Hannah",
                            IsTwoFactorEnabled = false,
                            LastName = "HR",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$l5bk3/KI984U6CFLnOcDreAnknvnsznw6aEbG5fONDce7.a09nRYm",
                            Role = 2,
                            Status = 0
                        });
                });

            modelBuilder.Entity("PayRexApplication.Models.UserLoginAttempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attemptId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptId"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attemptCount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ipAddress");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("isLocked");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastAttemptAt");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("lockUntil");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("reason");

                    b.Property<bool>("Success")
                        .HasColumnType("bit")
                        .HasColumnName("success");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("userAgent");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("AttemptId");

                    b.HasIndex("Email");

                    b.HasIndex("UserId");

                    b.ToTable("userLoginAttempts");
                });

            modelBuilder.Entity("PayRexApplication.Models.AttendanceRecord", b =>
                {
                    b.HasOne("PayRexApplication.Models.Company", "Company")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PayRexApplication.Models.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayRexApplication.Models.AttendanceScan", b =>
                {
                    b.HasOne("PayRexApplication.Models.Employee", "Employee")
                        .WithMany("AttendanceScans")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayRexApplication.Models.AuditLog", b =>
                {
                    b.HasOne("PayRexApplication.Models.Company", "Company")
                        .WithMany("AuditLogs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PayRexApplication.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PayRexApplication.Models.BillingInvoice", b =>
                {
                    b.HasOne("PayRexApplication.Models.Company", "Company")
                        .WithMany("BillingInvoices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PayRexApplication.Models.Company", b =>
                {
                    b.HasOne("PayRexApplication.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Companies")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("PayRexApplication.Models.CompanySetting", b =>
                {
                    b.HasOne("PayRexApplication.Models.Company", "Company")
                        .WithOne("CompanySetting")
                        .HasForeignKey("PayRexApplication.Models.CompanySetting", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PayRexApplication.Models.Employee", b =>
                {
                    b.HasOne("PayRexApplication.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayRexApplication.Models.EmployeeRole", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PayRexApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PayRexApplication.Models.EmployeeBenefit", b =>
                {
                    b.HasOne("PayRexApplication.Models.Employee", "Employee")
                        .WithMany("EmployeeBenefits")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayRexApplication.Models.EmployeeDeduction", b =>
                {
                    b.HasOne("PayRexApplication.Models.Employee", "Employee")
                        .WithMany("EmployeeDeductions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayRexApplication.Models.EmployeeQrCode", b =>
                {
                    b.HasOne("PayRexApplication.Models.Employee", "Employee")
                        .WithOne("EmployeeQrCode")
                        .HasForeignKey("PayRexApplication.Models.EmployeeQrCode", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayRexApplication.Models.EmployeeRole", b =>
                {
                    b.HasOne("PayRexApplication.Models.Company", "Company")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PayRexApplication.Models.GovernmentContribution", b =>
                {
                    b.HasOne("PayRexApplication.Models.Employee", "Employee")
                        .WithMany("GovernmentContributions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayRexApplication.Models.PayrollPeriod", "PayrollPeriod")
                        .WithMany("GovernmentContributions")
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollPeriod");
                });

            modelBuilder.Entity("PayRexApplication.Models.Payment", b =>
                {
                    b.HasOne("PayRexApplication.Models.BillingInvoice", "BillingInvoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingInvoice");
                });

            modelBuilder.Entity("PayRexApplication.Models.PayrollApproval", b =>
                {
                    b.HasOne("PayRexApplication.Models.User", "ApprovedByUser")
                        .WithMany("PayrollApprovals")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PayRexApplication.Models.PayrollPeriod", "PayrollPeriod")
                        .WithMany("PayrollApprovals")
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("PayrollPeriod");
                });

            modelBuilder.Entity("PayRexApplication.Models.PayrollPeriod", b =>
                {
                    b.HasOne("PayRexApplication.Models.Company", "Company")
                        .WithMany("PayrollPeriods")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PayRexApplication.Models.PayrollSummary", b =>
                {
                    b.HasOne("PayRexApplication.Models.Employee", "Employee")
                        .WithMany("PayrollSummaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PayRexApplication.Models.PayrollPeriod", "PayrollPeriod")
                        .WithMany("PayrollSummaries")
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollPeriod");
                });

            modelBuilder.Entity("PayRexApplication.Models.Payslip", b =>
                {
                    b.HasOne("PayRexApplication.Models.PayrollSummary", "PayrollSummary")
                        .WithOne("Payslip")
                        .HasForeignKey("PayRexApplication.Models.Payslip", "PayrollSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayrollSummary");
                });

            modelBuilder.Entity("PayRexApplication.Models.Subscription", b =>
                {
                    b.HasOne("PayRexApplication.Models.Company", "Company")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayRexApplication.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("PayRexApplication.Models.User", b =>
                {
                    b.HasOne("PayRexApplication.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PayRexApplication.Models.UserLoginAttempt", b =>
                {
                    b.HasOne("PayRexApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PayRexApplication.Models.BillingInvoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PayRexApplication.Models.Company", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("AuditLogs");

                    b.Navigation("BillingInvoices");

                    b.Navigation("CompanySetting");

                    b.Navigation("EmployeeRoles");

                    b.Navigation("Employees");

                    b.Navigation("PayrollPeriods");

                    b.Navigation("Subscriptions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PayRexApplication.Models.Employee", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("AttendanceScans");

                    b.Navigation("EmployeeBenefits");

                    b.Navigation("EmployeeDeductions");

                    b.Navigation("EmployeeQrCode");

                    b.Navigation("GovernmentContributions");

                    b.Navigation("PayrollSummaries");
                });

            modelBuilder.Entity("PayRexApplication.Models.EmployeeRole", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PayRexApplication.Models.PayrollPeriod", b =>
                {
                    b.Navigation("GovernmentContributions");

                    b.Navigation("PayrollApprovals");

                    b.Navigation("PayrollSummaries");
                });

            modelBuilder.Entity("PayRexApplication.Models.PayrollSummary", b =>
                {
                    b.Navigation("Payslip");
                });

            modelBuilder.Entity("PayRexApplication.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("PayRexApplication.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("PayrollApprovals");
                });
#pragma warning restore 612, 618
        }
    }
}
