using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PayRex.API.Migrations
{
    /// <inheritdoc />
    public partial class AddFinanceEntriesAndSystemNotifications : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<decimal>(
                name: "vatAmount",
                table: "billingInvoices",
                type: "decimal(18,2)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.CreateTable(
                name: "financeEntries",
                columns: table => new
                {
                    entryId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    type = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    description = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    amount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    vatAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    category = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    reference = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    isAutoGenerated = table.Column<bool>(type: "bit", nullable: false),
                    createdAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    createdBy = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_financeEntries", x => x.entryId);
                });

            migrationBuilder.CreateTable(
                name: "systemNotifications",
                columns: table => new
                {
                    notificationId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    title = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    message = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: false),
                    type = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    targetRoles = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    isActive = table.Column<bool>(type: "bit", nullable: false),
                    createdAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    createdBy = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_systemNotifications", x => x.notificationId);
                });

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 1,
                column: "passwordHash",
                value: "$2a$11$4/Be9fB.kAu0aNQJj1z/te5oCLNZzmo8HLgse9B4vW7r9QgoIB.te");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 2,
                column: "passwordHash",
                value: "$2a$11$wncMZ6v.EMamgCDqlLWHYOWDTVagC/umOxet9TETnturZpN76Umii");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 3,
                column: "passwordHash",
                value: "$2a$11$4VXDIRMmp645NR/.yckSQuRwGhJSIC71X3/huI56g0n2nI7IBCqpa");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 4,
                column: "passwordHash",
                value: "$2a$11$kaXYPZ0pc4WTuFNDMMxOu.GIZYPMDY2RKwNxDUDGpa2Ls9dde8pRu");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 5,
                column: "passwordHash",
                value: "$2a$11$1ct3nl5djmiXbHOnJclrJuGYSYVaka.CQYTRncWW0cPfhpsfYK8zm");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 6,
                column: "passwordHash",
                value: "$2a$11$84dy53jznpdOAdY7E2gLZeDuEsJM25l3bqSiUzy8MDn/KjDcxoeGm");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 7,
                column: "passwordHash",
                value: "$2a$11$BGdIBqAEPZw6/Wr2zkssWehpMybqWTSUA285Y0UL7Ks3tMyrES6J.");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 8,
                column: "passwordHash",
                value: "$2a$11$ySmzbRInLrVuGghLg5AtLuC6W9CgvugzCsC7wAd2y4VRowfkm.Vgu");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 9,
                column: "passwordHash",
                value: "$2a$11$51JNfW/Y2BdyHJXEtOeyj.vCoMQZMH4P/HxPQ4STRxXYkAZN4MEqW");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 10,
                column: "passwordHash",
                value: "$2a$11$d/0mN0YErsFnphLHTT1XKeeOoTT2dTCkqbhCa1kz/vtHeaROT4gp6");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 11,
                column: "passwordHash",
                value: "$2a$11$rpLD89tIZuYhWpcWZxbEFOAzn2zAO6VpUMNsLKxLTPEWOgej8oEeu");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 12,
                column: "passwordHash",
                value: "$2a$11$o8IsQupZxiyV.yonuYXTneVwMWAn6m4s8Ak3QduE/01dj.FBu5HnW");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "financeEntries");

            migrationBuilder.DropTable(
                name: "systemNotifications");

            migrationBuilder.DropColumn(
                name: "vatAmount",
                table: "billingInvoices");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 1,
                column: "passwordHash",
                value: "$2a$11$oZ5jqDa7cS3QtFwpA7fv3Oc7aEZ3wcw5CkH0nbNbMSjm7TIN3elSi");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 2,
                column: "passwordHash",
                value: "$2a$11$600JeAHxIYQQVdWmMhf5AuzOsprnuU3V3vWY6olUW18Q0eMv/b2Ra");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 3,
                column: "passwordHash",
                value: "$2a$11$xAXOPtHOrjlfz1OdB8i0junhkhZ5.dxssqkiAYZKK4ZsxKCvRPDYu");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 4,
                column: "passwordHash",
                value: "$2a$11$HZbnk1uB0ENzOEtRrC5xPutxJfDQ6/AJaeAMEnM9dslZW9Vd5mYxu");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 5,
                column: "passwordHash",
                value: "$2a$11$or94L3C8Fh5WzkgTJftQ3.H7RgxDeBIFi1VpX2F../OUwk8KIMPl2");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 6,
                column: "passwordHash",
                value: "$2a$11$plgEVq8uUNvEGTENdlhnE.tXm.dEQDVPS0rrL.Xrhq5wyjG37rZv.");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 7,
                column: "passwordHash",
                value: "$2a$11$GxSQuNNr4z6SnvCme8WT2ORok/QeuKgROAss1fJgSfNVUf79FvAK2");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 8,
                column: "passwordHash",
                value: "$2a$11$ookKTCsnne.mQgf8dpQzr.mCfKUi4Q3O7BAJwsGZ19zc6IKtDcj7C");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 9,
                column: "passwordHash",
                value: "$2a$11$yFSh8dS5ettid6EQbywyIeRxgTPhRu45PqQL0WY6JhG36CaN4K.KS");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 10,
                column: "passwordHash",
                value: "$2a$11$qZssRIHgfhxfNxVHVxbDuu7twM.67MZFuWTJ5MzYj3Xh9gwXbtXlS");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 11,
                column: "passwordHash",
                value: "$2a$11$pYUJcL572KicblJ7PzZJ0Ow2iGQ0ljmxZ0XlvgihP547XuXcWF.Qa");

            migrationBuilder.UpdateData(
                table: "users",
                keyColumn: "userId",
                keyValue: 12,
                column: "passwordHash",
                value: "$2a$11$/ZGwfb.RQiTntFZQOkfsUO5App9DXP4gCP9f6lTJPkairY.Y98pk.");
        }
    }
}
