using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace PayRex.Web.Pages.Admin
{
    [Authorize(Roles = "SuperAdmin")]
    public class FinanceModel : PageModel
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly ILogger<FinanceModel> _logger;

        public List<FinanceEntryItem> Entries { get; set; } = new();
        public FinanceSummaryItem Summary { get; set; } = new();
        [TempData] public string? StatusMessage { get; set; }

        public FinanceModel(IHttpClientFactory httpClientFactory, ILogger<FinanceModel> logger)
        {
            _httpClientFactory = httpClientFactory;
            _logger = logger;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            if (!Request.Cookies.TryGetValue("PayRex.AuthToken", out var token)) return RedirectToPage("/Auth/Login");

            var client = _httpClientFactory.CreateClient("PayRexApi");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            var opts = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };

            try
            {
                var entriesTask = client.GetAsync("api/superadmin/finance");
                var summaryTask = client.GetAsync("api/superadmin/finance/summary");
                await Task.WhenAll(entriesTask, summaryTask);

                if (entriesTask.Result.IsSuccessStatusCode)
                    Entries = JsonSerializer.Deserialize<List<FinanceEntryItem>>(await entriesTask.Result.Content.ReadAsStringAsync(), opts) ?? new();

                if (summaryTask.Result.IsSuccessStatusCode)
                    Summary = JsonSerializer.Deserialize<FinanceSummaryItem>(await summaryTask.Result.Content.ReadAsStringAsync(), opts) ?? new();
            }
            catch (Exception ex) { _logger.LogError(ex, "Error loading finance data"); }

            return Page();
        }

        public async Task<IActionResult> OnPostAddEntryAsync(string type, string description, decimal amount, string? category, string? reference)
        {
            if (!Request.Cookies.TryGetValue("PayRex.AuthToken", out var token)) return RedirectToPage("/Auth/Login");

            var client = _httpClientFactory.CreateClient("PayRexApi");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            var body = new StringContent(JsonSerializer.Serialize(new { type, description, amount, category, reference }), Encoding.UTF8, "application/json");
            var response = await client.PostAsync("api/superadmin/finance", body);
            StatusMessage = response.IsSuccessStatusCode ? "Finance entry added successfully" : "Failed to add finance entry";

            return RedirectToPage();
        }

        public class FinanceEntryItem
        {
            public int EntryId { get; set; }
            public string Type { get; set; } = "";
            public string Description { get; set; } = "";
            public decimal Amount { get; set; }
            public decimal VatAmount { get; set; }
            public string? Category { get; set; }
            public string? Reference { get; set; }
            public bool IsAutoGenerated { get; set; }
            public DateTime CreatedAt { get; set; }
        }

        public class FinanceSummaryItem
        {
            public decimal TotalIncome { get; set; }
            public decimal TotalDeductions { get; set; }
            public decimal TotalVat { get; set; }
            public decimal NetProfit { get; set; }
            public int EntryCount { get; set; }
        }
    }
}
