using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PayRexApplication.Models
{
    [Table("financeEntries")]
    public class FinanceEntry
    {
        [Key]
        [Column("entryId")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int EntryId { get; set; }

        [Required]
        [MaxLength(20)]
        [Column("type")]
        public string Type { get; set; } = string.Empty; // "Income" or "Deduction"

        [Required]
        [MaxLength(200)]
        [Column("description")]
        public string Description { get; set; } = string.Empty;

        [Required]
        [Column("amount", TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }

        [Column("vatAmount", TypeName = "decimal(18,2)")]
        public decimal VatAmount { get; set; }

        [MaxLength(100)]
        [Column("category")]
        public string? Category { get; set; }

        [MaxLength(200)]
        [Column("reference")]
        public string? Reference { get; set; }

        [Column("isAutoGenerated")]
        public bool IsAutoGenerated { get; set; }

        [Column("createdAt")]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        [Column("createdBy")]
        public int? CreatedBy { get; set; }

        /// <summary>
        /// When set, this entry belongs to a specific company (e.g. subscription cost).
        /// When null, it is a SuperAdmin-level global entry (e.g. subscription income).
        /// </summary>
        [Column("companyId")]
        public int? CompanyId { get; set; }
    }
}
